name: candidate_card
version: 0.0.2
author: James Hurford <terrasea@gmail.com>
description: A card for displaying a picture, summary and link to more info of a candidate
homepage: https://github.com/nzgreens/candidate_card.git
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  polymer: ">=1.0.0-rc.2 <2.0.0"
  polymer_interop: ">=1.0.0-rc.1 <2.0.0"
  web_components: ">=0.12.0+3 <0.13.0"
  reflectable: '>=0.4.0 <1.0.0'

  polymer_elements: ">=1.0.0-rc.2 < 2.0.0"
dev_dependencies:
  browser: any
  test: any
transformers:
- web_components:
    entry_points:
    - test/index.html
    - example/index.html
- reflectable:
    entry_points:
    - test/test.dart
    - example/main.dart
- test/pub_serve:
    $include: test/test.dart
- $dart2js:
    minify: false